// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

import Layout from "@/components/ui/layout";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Sidebar } from "@/components/ui/layout/sidebar";
import SizesExample from "./examples/sizes";
import SpacingExample from "./examples/spacing";
import InsetsExample from "./examples/insets";
import UIColorsExample from "./examples/ui-colors";
import PaletteColorsExample from "./examples/palette-colors";
import GraysExample from "./examples/grays";
import PaletteShadesExample from "./examples/palette-shades";
import AspectsExample from "./examples/aspects";

type SectionsType = Array<[string, string, React.ReactNode]>;

const sections: SectionsType = [
  ["Sizes", "sizes", <SizesExample key="sizes" />],
  ["Spacing", "spacing", <SpacingExample key="spacing" />],
  ["Insets", "insets", <InsetsExample key="insets" />],
  ["UI Colors", "ui-colors", <UIColorsExample key="ui-colors" />],
  ["Palette Colors", "palette-colors", <PaletteColorsExample key="palette-colors" />],
  ["Grays", "grays", <GraysExample key="grays" />],
  ["Palette Color Shades", "palette-shades", <PaletteShadesExample key="palette-shades" />],
  ["Aspects", "aspects", <AspectsExample key="aspects" />],
];

function SectionHeader({ index }: { index: number }) {
  const [title, id] = sections[index];

  return (
    <h2 className="text-lg font-bold">
      <span id={`${id}-title`}>{title}</span>
      {index < sections.length - 1 && (
        <a href={`#${sections[index + 1][1]}`} className="sr-nav-link">
          Skip to {sections[index + 1][0]}
        </a>
      )}
      {index > 0 && (
        <a href={`#${sections[index - 1][1]}`} className="sr-nav-link">
          Back to {sections[index - 1][0]}
        </a>
      )}
    </h2>
  );
}

function Section({ index }: { index: number }) {
  const [title, id, content] = sections[index];

  return (
    <div
      className="flex flex-col gap-4 p-md w-full grow"
      id={id}
      aria-labelledby={`${id}-title`}
      aria-description={`${title} Section`}
    >
      <SectionHeader index={index} />
      {content}
    </div>
  );
}

function PageHeader() {
  return (
    <header className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <Badge>TailwindCSS</Badge>
        <Badge variant="secondary">Kitchen Sink</Badge>
        <Badge variant="outline">Catpuccin latte/mocha</Badge>
      </div>
      <div className="space-y-2">
        <h1>Completely WCAG Compliant TailwindCSS Kitchen Sink</h1>
        <p>
          A dense reference page for every tailwindcss primitive in this repo,
          grouped by how you actually reach for them in product work.
        </p>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Table of Contents</CardTitle>
          <CardDescription>
            Each section uses only the local shadcn components in this codebase.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <nav>
            <ul>
              {sections.map(([title, id]) => (
                <li key={id}>
                  <a href={`#${id}`}>{title}</a>
                </li>
              ))}
            </ul>
          </nav>
        </CardContent>
      </Card>
    </header>
  );
}

export default function TailwindCSS() {
  return (
    <Layout variant="sidebar">
      <Sidebar sections={sections} />
      <div className="flex flex-col place-items-stretch place-content-stretch w-full *:p-md *:w-full *:grow">
        <PageHeader />
        <main className="space-y-10" id="main" role="main">
          {sections.map((_, index) => (
            <Section key={sections[index][1]} index={index} />
          ))}
        </main>
      </div>
    </Layout>
  );
}
