// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function AspectsExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-row flex-wrap gap-4">
          <div className="w-32">
            <div className="aspect-video border border-border flex items-center justify-center text-muted-foreground">
              video
            </div>
          </div>
          <div className="w-32">
            <div className="aspect-square border border-border flex items-center justify-center text-muted-foreground">
              square
            </div>
          </div>
          <div className="w-32">
            <div className="aspect-golden border border-border flex items-center justify-center text-muted-foreground">
              golden
            </div>
          </div>
          <div className="w-32">
            <div className="aspect-retro border border-border flex items-center justify-center text-muted-foreground">
              retro
            </div>
          </div>
          <div className="w-32">
            <div className="aspect-portrait border border-border flex items-center justify-center text-muted-foreground">
              portrait
            </div>
          </div>
          <div className="w-32">
            <div className="aspect-panorama border border-border flex items-center justify-center text-muted-foreground">
              panorama
            </div>
          </div>
          <div className="w-32">
            <div className="aspect-imax border border-border flex items-center justify-center text-muted-foreground">
              imax
            </div>
          </div>
          </div>
    </div>
  );
}
