// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function GraysExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-2">
            <h3>text</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="text-text text-xs">
                text text
              </div>
              <div className="text-subtext-1 text-xs">
                text subtext-1
              </div>
              <div className="text-subtext-0 text-xs">
                text subtext-0
              </div>
              <div className="text-overlay-2 text-xs">
                text overlay-2
              </div>
              <div className="text-overlay-1 text-xs">
                text overlay-1
              </div>
              <div className="text-overlay-0 text-xs">
                text overlay-0
              </div>
              <div className="text-surface-2 text-xs">
                text surface-2
              </div>
              <div className="text-surface-1 text-xs">
                text surface-1
              </div>
              <div className="text-surface-0 text-xs">
                text surface-0
              </div>
              <div className="text-base text-xs">
                text base
              </div>
              <div className="text-mantle text-xs">
                text mantle
              </div>
              <div className="text-crust text-xs">
                text crust
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>bg</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="bg-text border border-border min-w-20 min-h-8 p-1 text-xs">
                bg text
              </div>
              <div className="bg-subtext-1 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg subtext-1
              </div>
              <div className="bg-subtext-0 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg subtext-0
              </div>
              <div className="bg-overlay-2 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg overlay-2
              </div>
              <div className="bg-overlay-1 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg overlay-1
              </div>
              <div className="bg-overlay-0 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg overlay-0
              </div>
              <div className="bg-surface-2 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg surface-2
              </div>
              <div className="bg-surface-1 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg surface-1
              </div>
              <div className="bg-surface-0 border border-border min-w-20 min-h-8 p-1 text-xs">
                bg surface-0
              </div>
              <div className="bg-base border border-border min-w-20 min-h-8 p-1 text-xs">
                bg base
              </div>
              <div className="bg-mantle border border-border min-w-20 min-h-8 p-1 text-xs">
                bg mantle
              </div>
              <div className="bg-crust border border-border min-w-20 min-h-8 p-1 text-xs">
                bg crust
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>border</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="border-text border border-border min-w-20 min-h-8 p-1 text-xs">
                border text
              </div>
              <div className="border-subtext-1 border border-border min-w-20 min-h-8 p-1 text-xs">
                border subtext-1
              </div>
              <div className="border-subtext-0 border border-border min-w-20 min-h-8 p-1 text-xs">
                border subtext-0
              </div>
              <div className="border-overlay-2 border border-border min-w-20 min-h-8 p-1 text-xs">
                border overlay-2
              </div>
              <div className="border-overlay-1 border border-border min-w-20 min-h-8 p-1 text-xs">
                border overlay-1
              </div>
              <div className="border-overlay-0 border border-border min-w-20 min-h-8 p-1 text-xs">
                border overlay-0
              </div>
              <div className="border-surface-2 border border-border min-w-20 min-h-8 p-1 text-xs">
                border surface-2
              </div>
              <div className="border-surface-1 border border-border min-w-20 min-h-8 p-1 text-xs">
                border surface-1
              </div>
              <div className="border-surface-0 border border-border min-w-20 min-h-8 p-1 text-xs">
                border surface-0
              </div>
              <div className="border-base border border-border min-w-20 min-h-8 p-1 text-xs">
                border base
              </div>
              <div className="border-mantle border border-border min-w-20 min-h-8 p-1 text-xs">
                border mantle
              </div>
              <div className="border-crust border border-border min-w-20 min-h-8 p-1 text-xs">
                border crust
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>shadow</h3>
            <div className="flex flex-row flex-wrap gap-2 *:shadow-md">
              <div className="shadow-text shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow text
              </div>
              <div className="shadow-subtext-1 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow subtext-1
              </div>
              <div className="shadow-subtext-0 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow subtext-0
              </div>
              <div className="shadow-overlay-2 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow overlay-2
              </div>
              <div className="shadow-overlay-1 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow overlay-1
              </div>
              <div className="shadow-overlay-0 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow overlay-0
              </div>
              <div className="shadow-surface-2 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow surface-2
              </div>
              <div className="shadow-surface-1 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow surface-1
              </div>
              <div className="shadow-surface-0 shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow surface-0
              </div>
              <div className="shadow-base shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow base
              </div>
              <div className="shadow-mantle shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow mantle
              </div>
              <div className="shadow-crust shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow crust
              </div>
            </div>
          </div>
    </div>
  );
}
