// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function InsetsExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-2">
            <h3>inset</h3>
            <div className="flex flex-row flex-wrap gap-4">
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-xs border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset xs
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-sm border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset sm
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-md border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset md
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-lg border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset lg
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-2x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 2x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-2xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 2xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-3x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 3x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-3xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 3xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-4x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 4x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-4xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 4xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-5x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 5x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-5xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 5xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-6x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 6x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-6xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 6xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-7x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 7x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-7xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 7xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-8x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 8x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-8xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 8xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-9x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 9x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-9xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset 9xl
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>inset-x</h3>
            <div className="flex flex-row flex-wrap gap-4">
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-xs border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x xs
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-sm border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x sm
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-md border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x md
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-lg border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x lg
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-2x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 2x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-2xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 2xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-3x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 3x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-3xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 3xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-4x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 4x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-4xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 4xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-5x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 5x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-5xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 5xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-6x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 6x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-6xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 6xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-7x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 7x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-7xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 7xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-8x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 8x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-8xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 8xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-9x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 9x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-x-9xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-x 9xl
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>inset-y</h3>
            <div className="flex flex-row flex-wrap gap-4">
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-xs border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y xs
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-sm border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y sm
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-md border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y md
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-lg border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y lg
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-2x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 2x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-2xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 2xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-3x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 3x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-3xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 3xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-4x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 4x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-4xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 4xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-5x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 5x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-5xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 5xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-6x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 6x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-6xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 6xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-7x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 7x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-7xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 7xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-8x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 8x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-8xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 8xl
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-9x border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 9x
                </div>
              </div>
              <div className="relative border border-border" style={{ width: "6rem", height: "4rem" }}>
                <div className="absolute inset-y-9xl border border-primary bg-primary/10 text-[0.5rem] text-primary p-0.5">
                  inset-y 9xl
                </div>
              </div>
            </div>
          </div>
    </div>
  );
}
