// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function PaletteColorsExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-2">
            <h3>text</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="text-rosewater text-xs">
                text rosewater
              </div>
              <div className="text-flamingo text-xs">
                text flamingo
              </div>
              <div className="text-pink text-xs">
                text pink
              </div>
              <div className="text-mauve text-xs">
                text mauve
              </div>
              <div className="text-red text-xs">
                text red
              </div>
              <div className="text-maroon text-xs">
                text maroon
              </div>
              <div className="text-peach text-xs">
                text peach
              </div>
              <div className="text-yellow text-xs">
                text yellow
              </div>
              <div className="text-green text-xs">
                text green
              </div>
              <div className="text-teal text-xs">
                text teal
              </div>
              <div className="text-sky text-xs">
                text sky
              </div>
              <div className="text-sapphire text-xs">
                text sapphire
              </div>
              <div className="text-blue text-xs">
                text blue
              </div>
              <div className="text-lavender text-xs">
                text lavender
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>bg</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="bg-rosewater border border-border min-w-20 min-h-8 p-1 text-xs">
                bg rosewater
              </div>
              <div className="bg-flamingo border border-border min-w-20 min-h-8 p-1 text-xs">
                bg flamingo
              </div>
              <div className="bg-pink border border-border min-w-20 min-h-8 p-1 text-xs">
                bg pink
              </div>
              <div className="bg-mauve border border-border min-w-20 min-h-8 p-1 text-xs">
                bg mauve
              </div>
              <div className="bg-red border border-border min-w-20 min-h-8 p-1 text-xs">
                bg red
              </div>
              <div className="bg-maroon border border-border min-w-20 min-h-8 p-1 text-xs">
                bg maroon
              </div>
              <div className="bg-peach border border-border min-w-20 min-h-8 p-1 text-xs">
                bg peach
              </div>
              <div className="bg-yellow border border-border min-w-20 min-h-8 p-1 text-xs">
                bg yellow
              </div>
              <div className="bg-green border border-border min-w-20 min-h-8 p-1 text-xs">
                bg green
              </div>
              <div className="bg-teal border border-border min-w-20 min-h-8 p-1 text-xs">
                bg teal
              </div>
              <div className="bg-sky border border-border min-w-20 min-h-8 p-1 text-xs">
                bg sky
              </div>
              <div className="bg-sapphire border border-border min-w-20 min-h-8 p-1 text-xs">
                bg sapphire
              </div>
              <div className="bg-blue border border-border min-w-20 min-h-8 p-1 text-xs">
                bg blue
              </div>
              <div className="bg-lavender border border-border min-w-20 min-h-8 p-1 text-xs">
                bg lavender
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>border</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="border-rosewater border border-border min-w-20 min-h-8 p-1 text-xs">
                border rosewater
              </div>
              <div className="border-flamingo border border-border min-w-20 min-h-8 p-1 text-xs">
                border flamingo
              </div>
              <div className="border-pink border border-border min-w-20 min-h-8 p-1 text-xs">
                border pink
              </div>
              <div className="border-mauve border border-border min-w-20 min-h-8 p-1 text-xs">
                border mauve
              </div>
              <div className="border-red border border-border min-w-20 min-h-8 p-1 text-xs">
                border red
              </div>
              <div className="border-maroon border border-border min-w-20 min-h-8 p-1 text-xs">
                border maroon
              </div>
              <div className="border-peach border border-border min-w-20 min-h-8 p-1 text-xs">
                border peach
              </div>
              <div className="border-yellow border border-border min-w-20 min-h-8 p-1 text-xs">
                border yellow
              </div>
              <div className="border-green border border-border min-w-20 min-h-8 p-1 text-xs">
                border green
              </div>
              <div className="border-teal border border-border min-w-20 min-h-8 p-1 text-xs">
                border teal
              </div>
              <div className="border-sky border border-border min-w-20 min-h-8 p-1 text-xs">
                border sky
              </div>
              <div className="border-sapphire border border-border min-w-20 min-h-8 p-1 text-xs">
                border sapphire
              </div>
              <div className="border-blue border border-border min-w-20 min-h-8 p-1 text-xs">
                border blue
              </div>
              <div className="border-lavender border border-border min-w-20 min-h-8 p-1 text-xs">
                border lavender
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>shadow</h3>
            <div className="flex flex-row flex-wrap gap-2 *:shadow-md">
              <div className="shadow-rosewater shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow rosewater
              </div>
              <div className="shadow-flamingo shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow flamingo
              </div>
              <div className="shadow-pink shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow pink
              </div>
              <div className="shadow-mauve shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow mauve
              </div>
              <div className="shadow-red shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow red
              </div>
              <div className="shadow-maroon shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow maroon
              </div>
              <div className="shadow-peach shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow peach
              </div>
              <div className="shadow-yellow shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow yellow
              </div>
              <div className="shadow-green shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow green
              </div>
              <div className="shadow-teal shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow teal
              </div>
              <div className="shadow-sky shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow sky
              </div>
              <div className="shadow-sapphire shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow sapphire
              </div>
              <div className="shadow-blue shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow blue
              </div>
              <div className="shadow-lavender shadow-xl min-w-20 min-h-8 p-1 text-xs">
                shadow lavender
              </div>
            </div>
          </div>
    </div>
  );
}
