// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function PaletteShadesExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-3">
            <h3>text</h3>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">rosewater</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-rosewater-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-rosewater-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-rosewater-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-rosewater-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-rosewater-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-rosewater-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-rosewater-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-rosewater-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-rosewater-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-rosewater-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">flamingo</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-flamingo-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-flamingo-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-flamingo-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-flamingo-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-flamingo-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-flamingo-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-flamingo-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-flamingo-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-flamingo-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-flamingo-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">pink</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-pink-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-pink-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-pink-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-pink-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-pink-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-pink-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-pink-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-pink-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-pink-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-pink-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">mauve</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-mauve-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-mauve-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-mauve-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-mauve-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-mauve-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-mauve-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-mauve-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-mauve-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-mauve-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-mauve-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">red</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-red-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-red-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-red-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-red-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-red-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-red-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-red-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-red-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-red-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-red-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">maroon</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-maroon-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-maroon-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-maroon-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-maroon-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-maroon-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-maroon-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-maroon-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-maroon-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-maroon-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-maroon-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">peach</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-peach-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-peach-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-peach-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-peach-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-peach-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-peach-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-peach-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-peach-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-peach-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-peach-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">yellow</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-yellow-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-yellow-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-yellow-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-yellow-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-yellow-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-yellow-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-yellow-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-yellow-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-yellow-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-yellow-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">green</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-green-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-green-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-green-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-green-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-green-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-green-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-green-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-green-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-green-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-green-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">teal</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-teal-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-teal-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-teal-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-teal-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-teal-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-teal-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-teal-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-teal-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-teal-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-teal-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sky</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-sky-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-sky-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-sky-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-sky-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-sky-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-sky-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-sky-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-sky-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-sky-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-sky-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sapphire</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-sapphire-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-sapphire-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-sapphire-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-sapphire-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-sapphire-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-sapphire-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-sapphire-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-sapphire-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-sapphire-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-sapphire-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">blue</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-blue-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-blue-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-blue-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-blue-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-blue-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-blue-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-blue-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-blue-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-blue-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-blue-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">lavender</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="text-lavender-100 text-[0.6rem]">
                    100
                  </div>
                  <div className="text-lavender-200 text-[0.6rem]">
                    200
                  </div>
                  <div className="text-lavender-300 text-[0.6rem]">
                    300
                  </div>
                  <div className="text-lavender-400 text-[0.6rem]">
                    400
                  </div>
                  <div className="text-lavender-500 text-[0.6rem]">
                    500
                  </div>
                  <div className="text-lavender-600 text-[0.6rem]">
                    600
                  </div>
                  <div className="text-lavender-700 text-[0.6rem]">
                    700
                  </div>
                  <div className="text-lavender-800 text-[0.6rem]">
                    800
                  </div>
                  <div className="text-lavender-900 text-[0.6rem]">
                    900
                  </div>
                  <div className="text-lavender-950 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
          </div>
          <div className="flex flex-col gap-3">
            <h3>bg</h3>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">rosewater</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-rosewater-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-rosewater-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-rosewater-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-rosewater-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-rosewater-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-rosewater-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-rosewater-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-rosewater-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-rosewater-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-rosewater-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">flamingo</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-flamingo-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-flamingo-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-flamingo-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-flamingo-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-flamingo-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-flamingo-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-flamingo-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-flamingo-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-flamingo-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-flamingo-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">pink</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-pink-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-pink-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-pink-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-pink-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-pink-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-pink-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-pink-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-pink-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-pink-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-pink-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">mauve</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-mauve-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-mauve-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-mauve-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-mauve-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-mauve-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-mauve-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-mauve-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-mauve-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-mauve-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-mauve-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">red</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-red-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-red-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-red-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-red-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-red-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-red-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-red-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-red-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-red-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-red-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">maroon</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-maroon-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-maroon-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-maroon-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-maroon-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-maroon-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-maroon-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-maroon-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-maroon-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-maroon-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-maroon-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">peach</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-peach-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-peach-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-peach-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-peach-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-peach-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-peach-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-peach-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-peach-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-peach-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-peach-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">yellow</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-yellow-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-yellow-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-yellow-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-yellow-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-yellow-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-yellow-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-yellow-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-yellow-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-yellow-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-yellow-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">green</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-green-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-green-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-green-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-green-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-green-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-green-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-green-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-green-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-green-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-green-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">teal</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-teal-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-teal-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-teal-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-teal-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-teal-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-teal-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-teal-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-teal-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-teal-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-teal-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sky</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-sky-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-sky-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-sky-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-sky-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-sky-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-sky-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-sky-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-sky-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-sky-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-sky-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sapphire</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-sapphire-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-sapphire-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-sapphire-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-sapphire-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-sapphire-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-sapphire-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-sapphire-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-sapphire-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-sapphire-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-sapphire-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">blue</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-blue-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-blue-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-blue-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-blue-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-blue-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-blue-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-blue-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-blue-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-blue-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-blue-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">lavender</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="bg-lavender-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="bg-lavender-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="bg-lavender-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="bg-lavender-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="bg-lavender-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="bg-lavender-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="bg-lavender-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="bg-lavender-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="bg-lavender-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="bg-lavender-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
          </div>
          <div className="flex flex-col gap-3">
            <h3>border</h3>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">rosewater</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-rosewater-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-rosewater-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-rosewater-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-rosewater-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-rosewater-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-rosewater-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-rosewater-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-rosewater-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-rosewater-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-rosewater-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">flamingo</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-flamingo-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-flamingo-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-flamingo-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-flamingo-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-flamingo-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-flamingo-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-flamingo-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-flamingo-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-flamingo-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-flamingo-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">pink</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-pink-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-pink-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-pink-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-pink-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-pink-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-pink-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-pink-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-pink-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-pink-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-pink-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">mauve</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-mauve-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-mauve-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-mauve-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-mauve-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-mauve-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-mauve-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-mauve-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-mauve-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-mauve-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-mauve-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">red</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-red-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-red-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-red-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-red-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-red-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-red-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-red-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-red-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-red-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-red-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">maroon</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-maroon-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-maroon-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-maroon-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-maroon-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-maroon-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-maroon-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-maroon-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-maroon-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-maroon-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-maroon-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">peach</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-peach-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-peach-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-peach-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-peach-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-peach-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-peach-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-peach-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-peach-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-peach-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-peach-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">yellow</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-yellow-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-yellow-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-yellow-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-yellow-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-yellow-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-yellow-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-yellow-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-yellow-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-yellow-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-yellow-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">green</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-green-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-green-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-green-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-green-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-green-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-green-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-green-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-green-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-green-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-green-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">teal</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-teal-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-teal-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-teal-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-teal-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-teal-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-teal-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-teal-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-teal-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-teal-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-teal-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sky</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-sky-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-sky-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-sky-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-sky-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-sky-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-sky-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-sky-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-sky-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-sky-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-sky-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sapphire</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-sapphire-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-sapphire-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-sapphire-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-sapphire-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-sapphire-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-sapphire-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-sapphire-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-sapphire-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-sapphire-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-sapphire-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">blue</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-blue-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-blue-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-blue-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-blue-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-blue-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-blue-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-blue-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-blue-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-blue-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-blue-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">lavender</span>
                <div className="flex flex-row flex-wrap gap-1">
                  <div className="border-lavender-100 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="border-lavender-200 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="border-lavender-300 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="border-lavender-400 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="border-lavender-500 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="border-lavender-600 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="border-lavender-700 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="border-lavender-800 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="border-lavender-900 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="border-lavender-950 border border-border min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
          </div>
          <div className="flex flex-col gap-3">
            <h3>shadow</h3>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">rosewater</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-rosewater-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-rosewater-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-rosewater-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-rosewater-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-rosewater-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-rosewater-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-rosewater-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-rosewater-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-rosewater-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-rosewater-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">flamingo</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-flamingo-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-flamingo-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-flamingo-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-flamingo-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-flamingo-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-flamingo-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-flamingo-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-flamingo-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-flamingo-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-flamingo-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">pink</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-pink-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-pink-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-pink-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-pink-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-pink-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-pink-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-pink-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-pink-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-pink-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-pink-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">mauve</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-mauve-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-mauve-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-mauve-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-mauve-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-mauve-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-mauve-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-mauve-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-mauve-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-mauve-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-mauve-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">red</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-red-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-red-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-red-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-red-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-red-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-red-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-red-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-red-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-red-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-red-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">maroon</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-maroon-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-maroon-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-maroon-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-maroon-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-maroon-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-maroon-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-maroon-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-maroon-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-maroon-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-maroon-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">peach</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-peach-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-peach-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-peach-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-peach-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-peach-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-peach-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-peach-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-peach-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-peach-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-peach-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">yellow</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-yellow-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-yellow-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-yellow-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-yellow-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-yellow-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-yellow-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-yellow-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-yellow-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-yellow-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-yellow-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">green</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-green-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-green-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-green-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-green-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-green-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-green-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-green-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-green-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-green-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-green-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">teal</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-teal-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-teal-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-teal-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-teal-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-teal-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-teal-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-teal-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-teal-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-teal-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-teal-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sky</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-sky-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-sky-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-sky-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-sky-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-sky-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-sky-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-sky-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-sky-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-sky-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-sky-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">sapphire</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-sapphire-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-sapphire-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-sapphire-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-sapphire-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-sapphire-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-sapphire-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-sapphire-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-sapphire-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-sapphire-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-sapphire-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">blue</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-blue-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-blue-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-blue-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-blue-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-blue-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-blue-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-blue-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-blue-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-blue-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-blue-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-muted-foreground">lavender</span>
                <div className="flex flex-row flex-wrap gap-1 *:shadow-md">
                  <div className="shadow-lavender-100 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    100
                  </div>
                  <div className="shadow-lavender-200 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    200
                  </div>
                  <div className="shadow-lavender-300 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    300
                  </div>
                  <div className="shadow-lavender-400 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    400
                  </div>
                  <div className="shadow-lavender-500 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    500
                  </div>
                  <div className="shadow-lavender-600 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    600
                  </div>
                  <div className="shadow-lavender-700 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    700
                  </div>
                  <div className="shadow-lavender-800 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    800
                  </div>
                  <div className="shadow-lavender-900 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    900
                  </div>
                  <div className="shadow-lavender-950 shadow-xl min-w-14 min-h-8 p-1 text-[0.6rem]">
                    950
                  </div>
                </div>
              </div>
          </div>
    </div>
  );
}
