// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function SizesExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-2">
            <h3>text</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="text-xs">
                text xs
              </div>
              <div className="text-sm">
                text sm
              </div>
              <div className="text-md">
                text md
              </div>
              <div className="text-lg">
                text lg
              </div>
              <div className="text-xl">
                text xl
              </div>
              <div className="text-2x">
                text 2x
              </div>
              <div className="text-2xl">
                text 2xl
              </div>
              <div className="text-3x">
                text 3x
              </div>
              <div className="text-3xl">
                text 3xl
              </div>
              <div className="text-4x">
                text 4x
              </div>
              <div className="text-4xl">
                text 4xl
              </div>
              <div className="text-5x">
                text 5x
              </div>
              <div className="text-5xl">
                text 5xl
              </div>
              <div className="text-6x">
                text 6x
              </div>
              <div className="text-6xl">
                text 6xl
              </div>
              <div className="text-7x">
                text 7x
              </div>
              <div className="text-7xl">
                text 7xl
              </div>
              <div className="text-8x">
                text 8x
              </div>
              <div className="text-8xl">
                text 8xl
              </div>
              <div className="text-9x">
                text 9x
              </div>
              <div className="text-9xl">
                text 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>size</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="size-xs border border-border">
                size xs
              </div>
              <div className="size-sm border border-border">
                size sm
              </div>
              <div className="size-md border border-border">
                size md
              </div>
              <div className="size-lg border border-border">
                size lg
              </div>
              <div className="size-xl border border-border">
                size xl
              </div>
              <div className="size-2x border border-border">
                size 2x
              </div>
              <div className="size-2xl border border-border">
                size 2xl
              </div>
              <div className="size-3x border border-border">
                size 3x
              </div>
              <div className="size-3xl border border-border">
                size 3xl
              </div>
              <div className="size-4x border border-border">
                size 4x
              </div>
              <div className="size-4xl border border-border">
                size 4xl
              </div>
              <div className="size-5x border border-border">
                size 5x
              </div>
              <div className="size-5xl border border-border">
                size 5xl
              </div>
              <div className="size-6x border border-border">
                size 6x
              </div>
              <div className="size-6xl border border-border">
                size 6xl
              </div>
              <div className="size-7x border border-border">
                size 7x
              </div>
              <div className="size-7xl border border-border">
                size 7xl
              </div>
              <div className="size-8x border border-border">
                size 8x
              </div>
              <div className="size-8xl border border-border">
                size 8xl
              </div>
              <div className="size-9x border border-border">
                size 9x
              </div>
              <div className="size-9xl border border-border">
                size 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>rounded</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="rounded-xs border border-border">
                rounded xs
              </div>
              <div className="rounded-sm border border-border">
                rounded sm
              </div>
              <div className="rounded-md border border-border">
                rounded md
              </div>
              <div className="rounded-lg border border-border">
                rounded lg
              </div>
              <div className="rounded-xl border border-border">
                rounded xl
              </div>
              <div className="rounded-2x border border-border">
                rounded 2x
              </div>
              <div className="rounded-2xl border border-border">
                rounded 2xl
              </div>
              <div className="rounded-3x border border-border">
                rounded 3x
              </div>
              <div className="rounded-3xl border border-border">
                rounded 3xl
              </div>
              <div className="rounded-4x border border-border">
                rounded 4x
              </div>
              <div className="rounded-4xl border border-border">
                rounded 4xl
              </div>
              <div className="rounded-5x border border-border">
                rounded 5x
              </div>
              <div className="rounded-5xl border border-border">
                rounded 5xl
              </div>
              <div className="rounded-6x border border-border">
                rounded 6x
              </div>
              <div className="rounded-6xl border border-border">
                rounded 6xl
              </div>
              <div className="rounded-7x border border-border">
                rounded 7x
              </div>
              <div className="rounded-7xl border border-border">
                rounded 7xl
              </div>
              <div className="rounded-8x border border-border">
                rounded 8x
              </div>
              <div className="rounded-8xl border border-border">
                rounded 8xl
              </div>
              <div className="rounded-9x border border-border">
                rounded 9x
              </div>
              <div className="rounded-9xl border border-border">
                rounded 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>block</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="block-xs border border-border">
                block xs
              </div>
              <div className="block-sm border border-border">
                block sm
              </div>
              <div className="block-md border border-border">
                block md
              </div>
              <div className="block-lg border border-border">
                block lg
              </div>
              <div className="block-xl border border-border">
                block xl
              </div>
              <div className="block-2x border border-border">
                block 2x
              </div>
              <div className="block-2xl border border-border">
                block 2xl
              </div>
              <div className="block-3x border border-border">
                block 3x
              </div>
              <div className="block-3xl border border-border">
                block 3xl
              </div>
              <div className="block-4x border border-border">
                block 4x
              </div>
              <div className="block-4xl border border-border">
                block 4xl
              </div>
              <div className="block-5x border border-border">
                block 5x
              </div>
              <div className="block-5xl border border-border">
                block 5xl
              </div>
              <div className="block-6x border border-border">
                block 6x
              </div>
              <div className="block-6xl border border-border">
                block 6xl
              </div>
              <div className="block-7x border border-border">
                block 7x
              </div>
              <div className="block-7xl border border-border">
                block 7xl
              </div>
              <div className="block-8x border border-border">
                block 8x
              </div>
              <div className="block-8xl border border-border">
                block 8xl
              </div>
              <div className="block-9x border border-border">
                block 9x
              </div>
              <div className="block-9xl border border-border">
                block 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>inline</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="inline-xs border border-border">
                inline xs
              </div>
              <div className="inline-sm border border-border">
                inline sm
              </div>
              <div className="inline-md border border-border">
                inline md
              </div>
              <div className="inline-lg border border-border">
                inline lg
              </div>
              <div className="inline-xl border border-border">
                inline xl
              </div>
              <div className="inline-2x border border-border">
                inline 2x
              </div>
              <div className="inline-2xl border border-border">
                inline 2xl
              </div>
              <div className="inline-3x border border-border">
                inline 3x
              </div>
              <div className="inline-3xl border border-border">
                inline 3xl
              </div>
              <div className="inline-4x border border-border">
                inline 4x
              </div>
              <div className="inline-4xl border border-border">
                inline 4xl
              </div>
              <div className="inline-5x border border-border">
                inline 5x
              </div>
              <div className="inline-5xl border border-border">
                inline 5xl
              </div>
              <div className="inline-6x border border-border">
                inline 6x
              </div>
              <div className="inline-6xl border border-border">
                inline 6xl
              </div>
              <div className="inline-7x border border-border">
                inline 7x
              </div>
              <div className="inline-7xl border border-border">
                inline 7xl
              </div>
              <div className="inline-8x border border-border">
                inline 8x
              </div>
              <div className="inline-8xl border border-border">
                inline 8xl
              </div>
              <div className="inline-9x border border-border">
                inline 9x
              </div>
              <div className="inline-9xl border border-border">
                inline 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>min-w</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="min-w-xs border border-border">
                min-w xs
              </div>
              <div className="min-w-sm border border-border">
                min-w sm
              </div>
              <div className="min-w-md border border-border">
                min-w md
              </div>
              <div className="min-w-lg border border-border">
                min-w lg
              </div>
              <div className="min-w-xl border border-border">
                min-w xl
              </div>
              <div className="min-w-2x border border-border">
                min-w 2x
              </div>
              <div className="min-w-2xl border border-border">
                min-w 2xl
              </div>
              <div className="min-w-3x border border-border">
                min-w 3x
              </div>
              <div className="min-w-3xl border border-border">
                min-w 3xl
              </div>
              <div className="min-w-4x border border-border">
                min-w 4x
              </div>
              <div className="min-w-4xl border border-border">
                min-w 4xl
              </div>
              <div className="min-w-5x border border-border">
                min-w 5x
              </div>
              <div className="min-w-5xl border border-border">
                min-w 5xl
              </div>
              <div className="min-w-6x border border-border">
                min-w 6x
              </div>
              <div className="min-w-6xl border border-border">
                min-w 6xl
              </div>
              <div className="min-w-7x border border-border">
                min-w 7x
              </div>
              <div className="min-w-7xl border border-border">
                min-w 7xl
              </div>
              <div className="min-w-8x border border-border">
                min-w 8x
              </div>
              <div className="min-w-8xl border border-border">
                min-w 8xl
              </div>
              <div className="min-w-9x border border-border">
                min-w 9x
              </div>
              <div className="min-w-9xl border border-border">
                min-w 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>w</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="w-xs border border-border">
                w xs
              </div>
              <div className="w-sm border border-border">
                w sm
              </div>
              <div className="w-md border border-border">
                w md
              </div>
              <div className="w-lg border border-border">
                w lg
              </div>
              <div className="w-xl border border-border">
                w xl
              </div>
              <div className="w-2x border border-border">
                w 2x
              </div>
              <div className="w-2xl border border-border">
                w 2xl
              </div>
              <div className="w-3x border border-border">
                w 3x
              </div>
              <div className="w-3xl border border-border">
                w 3xl
              </div>
              <div className="w-4x border border-border">
                w 4x
              </div>
              <div className="w-4xl border border-border">
                w 4xl
              </div>
              <div className="w-5x border border-border">
                w 5x
              </div>
              <div className="w-5xl border border-border">
                w 5xl
              </div>
              <div className="w-6x border border-border">
                w 6x
              </div>
              <div className="w-6xl border border-border">
                w 6xl
              </div>
              <div className="w-7x border border-border">
                w 7x
              </div>
              <div className="w-7xl border border-border">
                w 7xl
              </div>
              <div className="w-8x border border-border">
                w 8x
              </div>
              <div className="w-8xl border border-border">
                w 8xl
              </div>
              <div className="w-9x border border-border">
                w 9x
              </div>
              <div className="w-9xl border border-border">
                w 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>max-w</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="max-w-xs w-full border border-border">
                max-w xs
              </div>
              <div className="max-w-sm w-full border border-border">
                max-w sm
              </div>
              <div className="max-w-md w-full border border-border">
                max-w md
              </div>
              <div className="max-w-lg w-full border border-border">
                max-w lg
              </div>
              <div className="max-w-xl w-full border border-border">
                max-w xl
              </div>
              <div className="max-w-2x w-full border border-border">
                max-w 2x
              </div>
              <div className="max-w-2xl w-full border border-border">
                max-w 2xl
              </div>
              <div className="max-w-3x w-full border border-border">
                max-w 3x
              </div>
              <div className="max-w-3xl w-full border border-border">
                max-w 3xl
              </div>
              <div className="max-w-4x w-full border border-border">
                max-w 4x
              </div>
              <div className="max-w-4xl w-full border border-border">
                max-w 4xl
              </div>
              <div className="max-w-5x w-full border border-border">
                max-w 5x
              </div>
              <div className="max-w-5xl w-full border border-border">
                max-w 5xl
              </div>
              <div className="max-w-6x w-full border border-border">
                max-w 6x
              </div>
              <div className="max-w-6xl w-full border border-border">
                max-w 6xl
              </div>
              <div className="max-w-7x w-full border border-border">
                max-w 7x
              </div>
              <div className="max-w-7xl w-full border border-border">
                max-w 7xl
              </div>
              <div className="max-w-8x w-full border border-border">
                max-w 8x
              </div>
              <div className="max-w-8xl w-full border border-border">
                max-w 8xl
              </div>
              <div className="max-w-9x w-full border border-border">
                max-w 9x
              </div>
              <div className="max-w-9xl w-full border border-border">
                max-w 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>min-h</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="min-h-xs border border-border">
                min-h xs
              </div>
              <div className="min-h-sm border border-border">
                min-h sm
              </div>
              <div className="min-h-md border border-border">
                min-h md
              </div>
              <div className="min-h-lg border border-border">
                min-h lg
              </div>
              <div className="min-h-xl border border-border">
                min-h xl
              </div>
              <div className="min-h-2x border border-border">
                min-h 2x
              </div>
              <div className="min-h-2xl border border-border">
                min-h 2xl
              </div>
              <div className="min-h-3x border border-border">
                min-h 3x
              </div>
              <div className="min-h-3xl border border-border">
                min-h 3xl
              </div>
              <div className="min-h-4x border border-border">
                min-h 4x
              </div>
              <div className="min-h-4xl border border-border">
                min-h 4xl
              </div>
              <div className="min-h-5x border border-border">
                min-h 5x
              </div>
              <div className="min-h-5xl border border-border">
                min-h 5xl
              </div>
              <div className="min-h-6x border border-border">
                min-h 6x
              </div>
              <div className="min-h-6xl border border-border">
                min-h 6xl
              </div>
              <div className="min-h-7x border border-border">
                min-h 7x
              </div>
              <div className="min-h-7xl border border-border">
                min-h 7xl
              </div>
              <div className="min-h-8x border border-border">
                min-h 8x
              </div>
              <div className="min-h-8xl border border-border">
                min-h 8xl
              </div>
              <div className="min-h-9x border border-border">
                min-h 9x
              </div>
              <div className="min-h-9xl border border-border">
                min-h 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>h</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="h-xs border border-border">
                h xs
              </div>
              <div className="h-sm border border-border">
                h sm
              </div>
              <div className="h-md border border-border">
                h md
              </div>
              <div className="h-lg border border-border">
                h lg
              </div>
              <div className="h-xl border border-border">
                h xl
              </div>
              <div className="h-2x border border-border">
                h 2x
              </div>
              <div className="h-2xl border border-border">
                h 2xl
              </div>
              <div className="h-3x border border-border">
                h 3x
              </div>
              <div className="h-3xl border border-border">
                h 3xl
              </div>
              <div className="h-4x border border-border">
                h 4x
              </div>
              <div className="h-4xl border border-border">
                h 4xl
              </div>
              <div className="h-5x border border-border">
                h 5x
              </div>
              <div className="h-5xl border border-border">
                h 5xl
              </div>
              <div className="h-6x border border-border">
                h 6x
              </div>
              <div className="h-6xl border border-border">
                h 6xl
              </div>
              <div className="h-7x border border-border">
                h 7x
              </div>
              <div className="h-7xl border border-border">
                h 7xl
              </div>
              <div className="h-8x border border-border">
                h 8x
              </div>
              <div className="h-8xl border border-border">
                h 8xl
              </div>
              <div className="h-9x border border-border">
                h 9x
              </div>
              <div className="h-9xl border border-border">
                h 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>max-h</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="max-h-xs h-full border border-border">
                max-h xs
              </div>
              <div className="max-h-sm h-full border border-border">
                max-h sm
              </div>
              <div className="max-h-md h-full border border-border">
                max-h md
              </div>
              <div className="max-h-lg h-full border border-border">
                max-h lg
              </div>
              <div className="max-h-xl h-full border border-border">
                max-h xl
              </div>
              <div className="max-h-2x h-full border border-border">
                max-h 2x
              </div>
              <div className="max-h-2xl h-full border border-border">
                max-h 2xl
              </div>
              <div className="max-h-3x h-full border border-border">
                max-h 3x
              </div>
              <div className="max-h-3xl h-full border border-border">
                max-h 3xl
              </div>
              <div className="max-h-4x h-full border border-border">
                max-h 4x
              </div>
              <div className="max-h-4xl h-full border border-border">
                max-h 4xl
              </div>
              <div className="max-h-5x h-full border border-border">
                max-h 5x
              </div>
              <div className="max-h-5xl h-full border border-border">
                max-h 5xl
              </div>
              <div className="max-h-6x h-full border border-border">
                max-h 6x
              </div>
              <div className="max-h-6xl h-full border border-border">
                max-h 6xl
              </div>
              <div className="max-h-7x h-full border border-border">
                max-h 7x
              </div>
              <div className="max-h-7xl h-full border border-border">
                max-h 7xl
              </div>
              <div className="max-h-8x h-full border border-border">
                max-h 8x
              </div>
              <div className="max-h-8xl h-full border border-border">
                max-h 8xl
              </div>
              <div className="max-h-9x h-full border border-border">
                max-h 9x
              </div>
              <div className="max-h-9xl h-full border border-border">
                max-h 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>p</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="p-xs border border-border">
                p xs
              </div>
              <div className="p-sm border border-border">
                p sm
              </div>
              <div className="p-md border border-border">
                p md
              </div>
              <div className="p-lg border border-border">
                p lg
              </div>
              <div className="p-xl border border-border">
                p xl
              </div>
              <div className="p-2x border border-border">
                p 2x
              </div>
              <div className="p-2xl border border-border">
                p 2xl
              </div>
              <div className="p-3x border border-border">
                p 3x
              </div>
              <div className="p-3xl border border-border">
                p 3xl
              </div>
              <div className="p-4x border border-border">
                p 4x
              </div>
              <div className="p-4xl border border-border">
                p 4xl
              </div>
              <div className="p-5x border border-border">
                p 5x
              </div>
              <div className="p-5xl border border-border">
                p 5xl
              </div>
              <div className="p-6x border border-border">
                p 6x
              </div>
              <div className="p-6xl border border-border">
                p 6xl
              </div>
              <div className="p-7x border border-border">
                p 7x
              </div>
              <div className="p-7xl border border-border">
                p 7xl
              </div>
              <div className="p-8x border border-border">
                p 8x
              </div>
              <div className="p-8xl border border-border">
                p 8xl
              </div>
              <div className="p-9x border border-border">
                p 9x
              </div>
              <div className="p-9xl border border-border">
                p 9xl
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>m</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="m-xs border border-border">
                m xs
              </div>
              <div className="m-sm border border-border">
                m sm
              </div>
              <div className="m-md border border-border">
                m md
              </div>
              <div className="m-lg border border-border">
                m lg
              </div>
              <div className="m-xl border border-border">
                m xl
              </div>
              <div className="m-2x border border-border">
                m 2x
              </div>
              <div className="m-2xl border border-border">
                m 2xl
              </div>
              <div className="m-3x border border-border">
                m 3x
              </div>
              <div className="m-3xl border border-border">
                m 3xl
              </div>
              <div className="m-4x border border-border">
                m 4x
              </div>
              <div className="m-4xl border border-border">
                m 4xl
              </div>
              <div className="m-5x border border-border">
                m 5x
              </div>
              <div className="m-5xl border border-border">
                m 5xl
              </div>
              <div className="m-6x border border-border">
                m 6x
              </div>
              <div className="m-6xl border border-border">
                m 6xl
              </div>
              <div className="m-7x border border-border">
                m 7x
              </div>
              <div className="m-7xl border border-border">
                m 7xl
              </div>
              <div className="m-8x border border-border">
                m 8x
              </div>
              <div className="m-8xl border border-border">
                m 8xl
              </div>
              <div className="m-9x border border-border">
                m 9x
              </div>
              <div className="m-9xl border border-border">
                m 9xl
              </div>
            </div>
          </div>
    </div>
  );
}
