// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function SpacingExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-2">
            <h3>space-x</h3>
            <div className="flex flex-row flex-wrap gap-4">
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">xs</span>
                <div className="flex space-x-xs">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">xs</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">sm</span>
                <div className="flex space-x-sm">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">sm</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">md</span>
                <div className="flex space-x-md">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">md</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">lg</span>
                <div className="flex space-x-lg">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">lg</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">xl</span>
                <div className="flex space-x-xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">2x</span>
                <div className="flex space-x-2x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">2x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">2xl</span>
                <div className="flex space-x-2xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">2xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">3x</span>
                <div className="flex space-x-3x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">3x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">3xl</span>
                <div className="flex space-x-3xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">3xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">4x</span>
                <div className="flex space-x-4x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">4x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">4xl</span>
                <div className="flex space-x-4xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">4xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">5x</span>
                <div className="flex space-x-5x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">5x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">5xl</span>
                <div className="flex space-x-5xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">5xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">6x</span>
                <div className="flex space-x-6x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">6x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">6xl</span>
                <div className="flex space-x-6xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">6xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">7x</span>
                <div className="flex space-x-7x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">7x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">7xl</span>
                <div className="flex space-x-7xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">7xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">8x</span>
                <div className="flex space-x-8x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">8x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">8xl</span>
                <div className="flex space-x-8xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">8xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">9x</span>
                <div className="flex space-x-9x">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">9x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">9xl</span>
                <div className="flex space-x-9xl">
                  <div className="border border-border p-1 text-xs">space-x</div>
                  <div className="border border-border p-1 text-xs">9xl</div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>space-y</h3>
            <div className="flex flex-row flex-wrap gap-4">
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">xs</span>
                <div className="flex flex-col space-y-xs">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">xs</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">sm</span>
                <div className="flex flex-col space-y-sm">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">sm</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">md</span>
                <div className="flex flex-col space-y-md">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">md</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">lg</span>
                <div className="flex flex-col space-y-lg">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">lg</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">xl</span>
                <div className="flex flex-col space-y-xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">2x</span>
                <div className="flex flex-col space-y-2x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">2x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">2xl</span>
                <div className="flex flex-col space-y-2xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">2xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">3x</span>
                <div className="flex flex-col space-y-3x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">3x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">3xl</span>
                <div className="flex flex-col space-y-3xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">3xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">4x</span>
                <div className="flex flex-col space-y-4x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">4x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">4xl</span>
                <div className="flex flex-col space-y-4xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">4xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">5x</span>
                <div className="flex flex-col space-y-5x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">5x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">5xl</span>
                <div className="flex flex-col space-y-5xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">5xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">6x</span>
                <div className="flex flex-col space-y-6x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">6x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">6xl</span>
                <div className="flex flex-col space-y-6xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">6xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">7x</span>
                <div className="flex flex-col space-y-7x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">7x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">7xl</span>
                <div className="flex flex-col space-y-7xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">7xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">8x</span>
                <div className="flex flex-col space-y-8x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">8x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">8xl</span>
                <div className="flex flex-col space-y-8xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">8xl</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">9x</span>
                <div className="flex flex-col space-y-9x">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">9x</div>
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-xs text-muted-foreground">9xl</span>
                <div className="flex flex-col space-y-9xl">
                  <div className="border border-border p-1 text-xs">space-y</div>
                  <div className="border border-border p-1 text-xs">9xl</div>
                </div>
              </div>
            </div>
          </div>
    </div>
  );
}
