// Auto-generated by scripts/generate-tailwind-kitchen-sink.mjs
// Do not edit manually — changes will be overwritten.

export default function UIColorsExample() {
  return (
    <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-2">
            <h3>text</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="text-primary-foreground text-xs">
                text primary-foreground
              </div>
              <div className="text-primary-hover text-xs">
                text primary-hover
              </div>
              <div className="text-primary text-xs">
                text primary
              </div>
              <div className="text-secondary-foreground text-xs">
                text secondary-foreground
              </div>
              <div className="text-secondary-hover text-xs">
                text secondary-hover
              </div>
              <div className="text-secondary text-xs">
                text secondary
              </div>
              <div className="text-accent-foreground text-xs">
                text accent-foreground
              </div>
              <div className="text-accent-hover text-xs">
                text accent-hover
              </div>
              <div className="text-accent text-xs">
                text accent
              </div>
              <div className="text-success-foreground text-xs">
                text success-foreground
              </div>
              <div className="text-success-hover text-xs">
                text success-hover
              </div>
              <div className="text-success text-xs">
                text success
              </div>
              <div className="text-destructive-foreground text-xs">
                text destructive-foreground
              </div>
              <div className="text-destructive-hover text-xs">
                text destructive-hover
              </div>
              <div className="text-destructive text-xs">
                text destructive
              </div>
              <div className="text-background text-xs">
                text background
              </div>
              <div className="text-foreground text-xs">
                text foreground
              </div>
              <div className="text-border text-xs">
                text border
              </div>
              <div className="text-ring text-xs">
                text ring
              </div>
              <div className="text-input text-xs">
                text input
              </div>
              <div className="text-card text-xs">
                text card
              </div>
              <div className="text-card-foreground text-xs">
                text card-foreground
              </div>
              <div className="text-chart-1 text-xs">
                text chart-1
              </div>
              <div className="text-chart-2 text-xs">
                text chart-2
              </div>
              <div className="text-chart-3 text-xs">
                text chart-3
              </div>
              <div className="text-chart-4 text-xs">
                text chart-4
              </div>
              <div className="text-chart-5 text-xs">
                text chart-5
              </div>
              <div className="text-muted-foreground text-xs">
                text muted-foreground
              </div>
              <div className="text-muted text-xs">
                text muted
              </div>
              <div className="text-popover-foreground text-xs">
                text popover-foreground
              </div>
              <div className="text-popover text-xs">
                text popover
              </div>
              <div className="text-sidebar-accent-foreground text-xs">
                text sidebar-accent-foreground
              </div>
              <div className="text-sidebar-accent text-xs">
                text sidebar-accent
              </div>
              <div className="text-sidebar-border text-xs">
                text sidebar-border
              </div>
              <div className="text-sidebar-foreground text-xs">
                text sidebar-foreground
              </div>
              <div className="text-sidebar-primary-foreground text-xs">
                text sidebar-primary-foreground
              </div>
              <div className="text-sidebar-primary text-xs">
                text sidebar-primary
              </div>
              <div className="text-sidebar-ring text-xs">
                text sidebar-ring
              </div>
              <div className="text-sidebar text-xs">
                text sidebar
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>bg</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="bg-primary-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg primary-foreground
              </div>
              <div className="bg-primary-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                bg primary-hover
              </div>
              <div className="bg-primary border border-border min-w-24 min-h-8 p-1 text-xs">
                bg primary
              </div>
              <div className="bg-secondary-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg secondary-foreground
              </div>
              <div className="bg-secondary-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                bg secondary-hover
              </div>
              <div className="bg-secondary border border-border min-w-24 min-h-8 p-1 text-xs">
                bg secondary
              </div>
              <div className="bg-accent-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg accent-foreground
              </div>
              <div className="bg-accent-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                bg accent-hover
              </div>
              <div className="bg-accent border border-border min-w-24 min-h-8 p-1 text-xs">
                bg accent
              </div>
              <div className="bg-success-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg success-foreground
              </div>
              <div className="bg-success-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                bg success-hover
              </div>
              <div className="bg-success border border-border min-w-24 min-h-8 p-1 text-xs">
                bg success
              </div>
              <div className="bg-destructive-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg destructive-foreground
              </div>
              <div className="bg-destructive-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                bg destructive-hover
              </div>
              <div className="bg-destructive border border-border min-w-24 min-h-8 p-1 text-xs">
                bg destructive
              </div>
              <div className="bg-background border border-border min-w-24 min-h-8 p-1 text-xs">
                bg background
              </div>
              <div className="bg-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg foreground
              </div>
              <div className="bg-border border border-border min-w-24 min-h-8 p-1 text-xs">
                bg border
              </div>
              <div className="bg-ring border border-border min-w-24 min-h-8 p-1 text-xs">
                bg ring
              </div>
              <div className="bg-input border border-border min-w-24 min-h-8 p-1 text-xs">
                bg input
              </div>
              <div className="bg-card border border-border min-w-24 min-h-8 p-1 text-xs">
                bg card
              </div>
              <div className="bg-card-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg card-foreground
              </div>
              <div className="bg-chart-1 border border-border min-w-24 min-h-8 p-1 text-xs">
                bg chart-1
              </div>
              <div className="bg-chart-2 border border-border min-w-24 min-h-8 p-1 text-xs">
                bg chart-2
              </div>
              <div className="bg-chart-3 border border-border min-w-24 min-h-8 p-1 text-xs">
                bg chart-3
              </div>
              <div className="bg-chart-4 border border-border min-w-24 min-h-8 p-1 text-xs">
                bg chart-4
              </div>
              <div className="bg-chart-5 border border-border min-w-24 min-h-8 p-1 text-xs">
                bg chart-5
              </div>
              <div className="bg-muted-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg muted-foreground
              </div>
              <div className="bg-muted border border-border min-w-24 min-h-8 p-1 text-xs">
                bg muted
              </div>
              <div className="bg-popover-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg popover-foreground
              </div>
              <div className="bg-popover border border-border min-w-24 min-h-8 p-1 text-xs">
                bg popover
              </div>
              <div className="bg-sidebar-accent-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar-accent-foreground
              </div>
              <div className="bg-sidebar-accent border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar-accent
              </div>
              <div className="bg-sidebar-border border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar-border
              </div>
              <div className="bg-sidebar-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar-foreground
              </div>
              <div className="bg-sidebar-primary-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar-primary-foreground
              </div>
              <div className="bg-sidebar-primary border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar-primary
              </div>
              <div className="bg-sidebar-ring border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar-ring
              </div>
              <div className="bg-sidebar border border-border min-w-24 min-h-8 p-1 text-xs">
                bg sidebar
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>border</h3>
            <div className="flex flex-row flex-wrap gap-2">
              <div className="border-primary-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border primary-foreground
              </div>
              <div className="border-primary-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                border primary-hover
              </div>
              <div className="border-primary border border-border min-w-24 min-h-8 p-1 text-xs">
                border primary
              </div>
              <div className="border-secondary-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border secondary-foreground
              </div>
              <div className="border-secondary-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                border secondary-hover
              </div>
              <div className="border-secondary border border-border min-w-24 min-h-8 p-1 text-xs">
                border secondary
              </div>
              <div className="border-accent-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border accent-foreground
              </div>
              <div className="border-accent-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                border accent-hover
              </div>
              <div className="border-accent border border-border min-w-24 min-h-8 p-1 text-xs">
                border accent
              </div>
              <div className="border-success-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border success-foreground
              </div>
              <div className="border-success-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                border success-hover
              </div>
              <div className="border-success border border-border min-w-24 min-h-8 p-1 text-xs">
                border success
              </div>
              <div className="border-destructive-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border destructive-foreground
              </div>
              <div className="border-destructive-hover border border-border min-w-24 min-h-8 p-1 text-xs">
                border destructive-hover
              </div>
              <div className="border-destructive border border-border min-w-24 min-h-8 p-1 text-xs">
                border destructive
              </div>
              <div className="border-background border border-border min-w-24 min-h-8 p-1 text-xs">
                border background
              </div>
              <div className="border-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border foreground
              </div>
              <div className="border-border border border-border min-w-24 min-h-8 p-1 text-xs">
                border border
              </div>
              <div className="border-ring border border-border min-w-24 min-h-8 p-1 text-xs">
                border ring
              </div>
              <div className="border-input border border-border min-w-24 min-h-8 p-1 text-xs">
                border input
              </div>
              <div className="border-card border border-border min-w-24 min-h-8 p-1 text-xs">
                border card
              </div>
              <div className="border-card-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border card-foreground
              </div>
              <div className="border-chart-1 border border-border min-w-24 min-h-8 p-1 text-xs">
                border chart-1
              </div>
              <div className="border-chart-2 border border-border min-w-24 min-h-8 p-1 text-xs">
                border chart-2
              </div>
              <div className="border-chart-3 border border-border min-w-24 min-h-8 p-1 text-xs">
                border chart-3
              </div>
              <div className="border-chart-4 border border-border min-w-24 min-h-8 p-1 text-xs">
                border chart-4
              </div>
              <div className="border-chart-5 border border-border min-w-24 min-h-8 p-1 text-xs">
                border chart-5
              </div>
              <div className="border-muted-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border muted-foreground
              </div>
              <div className="border-muted border border-border min-w-24 min-h-8 p-1 text-xs">
                border muted
              </div>
              <div className="border-popover-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border popover-foreground
              </div>
              <div className="border-popover border border-border min-w-24 min-h-8 p-1 text-xs">
                border popover
              </div>
              <div className="border-sidebar-accent-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar-accent-foreground
              </div>
              <div className="border-sidebar-accent border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar-accent
              </div>
              <div className="border-sidebar-border border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar-border
              </div>
              <div className="border-sidebar-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar-foreground
              </div>
              <div className="border-sidebar-primary-foreground border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar-primary-foreground
              </div>
              <div className="border-sidebar-primary border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar-primary
              </div>
              <div className="border-sidebar-ring border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar-ring
              </div>
              <div className="border-sidebar border border-border min-w-24 min-h-8 p-1 text-xs">
                border sidebar
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <h3>shadow</h3>
            <div className="flex flex-row flex-wrap gap-2 *:shadow-md">
              <div className="shadow-primary-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow primary-foreground
              </div>
              <div className="shadow-primary-hover shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow primary-hover
              </div>
              <div className="shadow-primary shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow primary
              </div>
              <div className="shadow-secondary-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow secondary-foreground
              </div>
              <div className="shadow-secondary-hover shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow secondary-hover
              </div>
              <div className="shadow-secondary shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow secondary
              </div>
              <div className="shadow-accent-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow accent-foreground
              </div>
              <div className="shadow-accent-hover shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow accent-hover
              </div>
              <div className="shadow-accent shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow accent
              </div>
              <div className="shadow-success-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow success-foreground
              </div>
              <div className="shadow-success-hover shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow success-hover
              </div>
              <div className="shadow-success shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow success
              </div>
              <div className="shadow-destructive-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow destructive-foreground
              </div>
              <div className="shadow-destructive-hover shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow destructive-hover
              </div>
              <div className="shadow-destructive shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow destructive
              </div>
              <div className="shadow-background shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow background
              </div>
              <div className="shadow-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow foreground
              </div>
              <div className="shadow-border shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow border
              </div>
              <div className="shadow-ring shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow ring
              </div>
              <div className="shadow-input shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow input
              </div>
              <div className="shadow-card shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow card
              </div>
              <div className="shadow-card-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow card-foreground
              </div>
              <div className="shadow-chart-1 shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow chart-1
              </div>
              <div className="shadow-chart-2 shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow chart-2
              </div>
              <div className="shadow-chart-3 shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow chart-3
              </div>
              <div className="shadow-chart-4 shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow chart-4
              </div>
              <div className="shadow-chart-5 shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow chart-5
              </div>
              <div className="shadow-muted-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow muted-foreground
              </div>
              <div className="shadow-muted shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow muted
              </div>
              <div className="shadow-popover-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow popover-foreground
              </div>
              <div className="shadow-popover shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow popover
              </div>
              <div className="shadow-sidebar-accent-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar-accent-foreground
              </div>
              <div className="shadow-sidebar-accent shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar-accent
              </div>
              <div className="shadow-sidebar-border shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar-border
              </div>
              <div className="shadow-sidebar-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar-foreground
              </div>
              <div className="shadow-sidebar-primary-foreground shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar-primary-foreground
              </div>
              <div className="shadow-sidebar-primary shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar-primary
              </div>
              <div className="shadow-sidebar-ring shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar-ring
              </div>
              <div className="shadow-sidebar shadow-xl min-w-24 min-h-8 p-1 text-xs">
                shadow sidebar
              </div>
            </div>
          </div>
    </div>
  );
}
